name: significado_sonho
description: Um app simples para interpretar sonhos
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.2.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
